services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000'
    environment:
      - NODE_ENV=production
    restart: unless-stopped
  # wwebjs_sessions:
  # Development version with volume mounting (uncomment for development)
  # web-dev:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - NODE_ENV=development
  #   volumes:
  #     - .:/app
  #     - /app/node_modules
  #     - /app/.next
  #   restart: unless-stopped
